name: scp
description: Servidor Centrar de Procesamiento de Piezas.

publish_to: 'none'

version: 1.4.5+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.4
  blur: ^3.1.0
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  desktop_drop: ^0.3.3
  dropdown_search: ^5.0.2
  extended_image: ^6.3.0
  file_picker: ^5.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fuzzywuzzy: ^0.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  html: ^0.15.0
  http: ^0.13.5
  http_parser: ^4.0.1
  intl: ^0.17.0
  just_audio: ^0.9.28
  just_audio_windows: ^0.1.0
  mime: ^1.0.2
  multi_split_view: ^2.1.0
  network_info_plus: ^2.1.4+1
  path: ^1.8.2
  path_provider: ^2.0.11
  pie_chart: ^5.3.2
  provider: ^6.0.3
  string_similarity: ^2.0.0
  url_launcher: ^6.1.5
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/
